services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Nginx.Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/app
  fpm:
    build:
      context: .
      dockerfile: ./docker/php/Fpm.Dockerfile
    volumes:
      - ./:/var/www/app
    networks:
      - internal
  pgsql:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    networks:
      - internal
    volumes:
      - ./var/db-data:/var/lib/postgresql/data
networks:
  internal: